apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: restaurant
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/restaurant_db
  SECRET_KEY: k8s-secret-change-me
