---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-ui
  namespace: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-ui
  template:
    metadata:
      labels:
        app: restaurant-ui
    spec:
      containers:
        - name: restaurant-ui
          image: ghcr.io/ashwinberyl/restaurant-ui:sha-0bdedeb9daf1845941e4424e0cc337da71551191
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-ui
  namespace: restaurant
spec:
  selector:
    app: restaurant-ui
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
